version: '3'
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 49153:49153
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=